version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        MODE: dev      # 🔁 Change to prod when needed
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: productdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: dev    # 🔁 Change to prod when needed
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
